-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2019-05-08 14:18:27.584
CREATE DATABASE BDVenta
go
USE BDVenta
go
-- tables
-- Table: DETALLE_VENTA
CREATE TABLE DETALLE_VENTA (
    CODDETVEN int  NOT NULL IDENTITY(1, 1),
    CANVEN int  NULL,
	SBTVEN int NULL,
    CODPRO int  NOT NULL,
    CONSTRAINT DETALLE_VENTA_pk PRIMARY KEY  (CODDETVEN)
);

-- Table: PERSONA
CREATE TABLE PERSONA (
    CODPER int  NOT NULL IDENTITY(1, 1),
    NOMPER varchar(50)  NULL,
    APEPER varchar(50)  NULL,
    DNIPER char(8)  NULL,
    FECNACPER varchar(10)  NULL,
    DIRPER varchar(50)  NULL,
    TELPER varchar(9)  NULL,
    ESTPER char(1)  NULL,
    CONSTRAINT PERSONA_pk PRIMARY KEY  (CODPER)
);

-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    CODPRO int  NOT NULL IDENTITY(1, 1),
    DESPRO varchar(50)  NULL,
    COSPRO varchar(4)  NULL,
    STCPRO int  NULL,
    ESTPRO char(1)  NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY  (CODPRO)
);

-- Table: VENTA
CREATE TABLE VENTA (
    CODVEN int  NOT NULL IDENTITY(1, 1),
    FECVEN varchar(10)  NULL,
    TOTVEN int  NULL,
    CODPER int  NOT NULL,
    CODDETVEN int  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY  (CODVEN)
);

-- foreign keys
-- Reference: DETALLE_VENTA_PRODUCTO (table: DETALLE_VENTA)
ALTER TABLE DETALLE_VENTA ADD CONSTRAINT DETALLE_VENTA_PRODUCTO
    FOREIGN KEY (CODPRO)
    REFERENCES PRODUCTO (CODPRO);

-- Reference: VENTA_DETALLE_VENTA (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_DETALLE_VENTA
    FOREIGN KEY (CODDETVEN)
    REFERENCES DETALLE_VENTA (CODDETVEN);

-- Reference: VENTA_PERSONA (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_PERSONA
    FOREIGN KEY (CODPER)
    REFERENCES PERSONA (CODPER)
go

CREATE VIEW vw_Persona
AS 
	SELECT CODPER,NOMPER,APEPER,DNIPER,FECNACPER,DIRPER,TELPER,case ESTPER when 'A' then 'Activo' when 'I' then 'Inactivo' end as ESTPER
	FROM PERSONA
go

CREATE VIEW vw_Producto
AS
	SELECT CODPRO,DESPRO,COSPRO,STCPRO,case ESTPRO when 'A' then 'Activo' when 'I' then 'Inactivo' end as ESTPRO
	FROM PRODUCTO
go

CREATE VIEW vw_Venta
AS
	SELECT CODVEN,FECVEN,TOTVEN,PERSONA.CODPER as CODPER,Concat(PERSONA.NOMPER,' ',PERSONA.APEPER) as Persona,DETALLE_VENTA.CODDETVEN as CODDETVEN,DETALLE_VENTA.SBTVEN as Detalle
	FROM VENTA
	inner join PERSONA
	on PERSONA.CODPER  = VENTA.CODVEN
	inner join DETALLE_VENTA
	on DETALLE_VENTA.CODDETVEN  = VENTA.CODDETVEN
go

CREATE VIEW vw_Venta_Detalle
AS
	SELECT CODDETVEN,CANVEN,SBTVEN,PRODUCTO.CODPRO as CODPRO,PRODUCTO.DESPRO as Producto
	FROM DETALLE_VENTA
	inner join PRODUCTO
	on PRODUCTO.CODPRO = DETALLE_VENTA.CODPRO
go

CREATE VIEW vw_Venta_Final
AS
	SELECT CODVEN,FECVEN,TOTVEN,PERSONA.CODPER as CODPER,Concat(PERSONA.NOMPER,' ',PERSONA.APEPER) as Persona,
		   DETALLE_VENTA.CODDETVEN as CODDETVEN,PRODUCTO.CODPRO as CODPRO,PRODUCTO.DESPRO as Producto,PRODUCTO.COSPRO as Costo,
		   DETALLE_VENTA.CANVEN as Cantidad,DETALLE_VENTA.SBTVEN as Subtotal
	FROM VENTA
	inner join PERSONA
	on PERSONA.CODPER = VENTA.CODPER
	inner join DETALLE_VENTA
	on DETALLE_VENTA.CODDETVEN  = VENTA.CODDETVEN
	inner join PRODUCTO
	on PRODUCTO.CODPRO = DETALLE_VENTA.CODPRO
go
-- End of file.

